# Generated by Django 6.0.2 on 2026-05-23 20:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_comments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="comments",
            new_name="Comment",
        ),
    ]
